dependencies:
  - smartcontractkit/chainlink-brownie-contracts@0.4.2
  - OpenZeppelin/openzeppelin-contracts@4.7.3
  
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.4.2'
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.7.3'
dotenv: .env

networks:
  default: development
  development:
    verify: False
  goerli:
    verify: True
    link_token: 0x326C977E6efc84E512bB9C30f76E30c160eD06FB
    VRF_coordinator: 0x2Ca8E0C643bDe4C2E08ab1fA0da3401AdAD7734D
    keyHash: 0x79d3d8832d904592c0bf9818b621522c988bb8b0c05cdc3b15aea1b6e8db0c15
    link_premium: 0.25
    callbackGasLimit: 100000
    requestConfirmations: 3
    numWords: 2
  mainnet-fork:
    verify: False
  mainnet-fork-dev:
    verify: False
  ganache-local:
    verify: False
wallets:
  from_key: ${PRIVATE_KEY}
